import { MUSIC_TRACKS, PVP_MUSIC } from '../config/audio-tracks.js';

export function createAudioSystem({THREE,getState,getCamera,getDesiredMusic}){
  const sound={ctx:null,master:null,compressor:null,noise:null,voices:0,muted:false,lastStep:0,lastMissile:0};
  const music={element:null,key:null,pvpIndex:-1,pvpRiseStarted:0,unlocked:false,volume:.78,failed:new Set()};

  function unlockAudio(){const state=getState();if(document.hidden||sound.muted)return null;music.unlocked=true;const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return null;if(!sound.ctx){const ctx=new AudioContextClass(),master=ctx.createGain(),compressor=ctx.createDynamicsCompressor();master.gain.value=.42;compressor.threshold.value=-16;compressor.knee.value=14;compressor.ratio.value=4;compressor.attack.value=.006;compressor.release.value=.2;master.connect(compressor).connect(ctx.destination);const noise=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*1.25),ctx.sampleRate),samples=noise.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=Math.random()*2-1;sound.ctx=ctx;sound.master=master;sound.compressor=compressor;sound.noise=noise}if(sound.ctx.state==='suspended')sound.ctx.resume().catch(()=>{});return sound.ctx}
  function soundBus(position,volume=.3){const ctx=unlockAudio();if(!ctx||sound.voices>=24)return null;const gain=ctx.createGain(),pan=ctx.createStereoPanner(),point=position?.position||position,camera=getCamera(),state=getState();if(point?.isVector3){const dx=point.x-camera.position.x,dz=point.z-camera.position.z,distance=Math.hypot(dx,dz),rightX=Math.cos(state.yaw),rightZ=-Math.sin(state.yaw);pan.pan.value=THREE.MathUtils.clamp((dx*rightX+dz*rightZ)/Math.max(1,distance),-1,1);volume/=1+distance*.055}const level=Math.max(.0001,volume);gain.gain.value=level;gain.connect(pan).connect(sound.master);sound.voices++;return{ctx,gain,level,finish:()=>{sound.voices=Math.max(0,sound.voices-1);gain.disconnect();pan.disconnect()}}}
  function soundTone(freq,endFreq,duration,volume,type='sine',position=null,delay=0){const bus=soundBus(position,volume);if(!bus)return;const {ctx,gain,level}=bus,osc=ctx.createOscillator(),start=ctx.currentTime+delay,finish=start+duration;osc.type=type;osc.frequency.setValueAtTime(Math.max(20,freq),start);osc.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),finish);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.linearRampToValueAtTime(level,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,finish);osc.connect(gain);osc.start(start);osc.stop(finish+.02);osc.onended=bus.finish}
  function soundNoise(duration,volume,position=null,filterType='lowpass',frequency=900,delay=0){const bus=soundBus(position,volume);if(!bus)return;const {ctx,gain,level}=bus,source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),start=ctx.currentTime+delay,finish=start+duration;source.buffer=sound.noise;source.loop=duration>sound.noise.duration;filter.type=filterType;filter.frequency.setValueAtTime(frequency,start);filter.frequency.exponentialRampToValueAtTime(Math.max(80,frequency*.35),finish);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.linearRampToValueAtTime(level,start+.008);gain.gain.exponentialRampToValueAtTime(.0001,finish);source.connect(filter).connect(gain);source.start(start,Math.random()*.2);source.stop(finish+.02);source.onended=bus.finish}
  function sfx(name,position=null,strength=1){const state=getState();if(document.hidden||state.tabSuspended||sound.muted)return;const v=Math.max(.05,Math.min(1.5,strength));switch(name){case'ui':soundTone(420,610,.075,.07*v,'sine');break;case'fireball':soundNoise(.28,.22*v,position,'lowpass',1100);soundTone(190,72,.36,.2*v,'sawtooth',position);break;case'fireImpact':soundNoise(.34,.32*v,position,'lowpass',780);soundTone(95,38,.3,.28*v,'sine',position);break;case'impact':soundNoise(.09,.18*v,position,'highpass',2600);soundTone(138,62,.15,.2*v,'triangle',position);soundTone(920,410,.07,.07*v,'square',position);break;case'missile':if(performance.now()-sound.lastMissile<55)break;sound.lastMissile=performance.now();soundNoise(.18,.15*v,position,'bandpass',1500);soundTone(310,125,.24,.12*v,'square',position);break;case'explosion':soundNoise(.5,.42*v,position,'lowpass',650);soundTone(82,28,.48,.34*v,'sine',position);break;case'lightning':soundNoise(.42,.28*v,position,'highpass',3200);for(let i=0;i<3;i++)soundTone(900+i*370,180+i*80,.1+i*.035,.065*v,'square',position,i*.035);break;case'fog':soundNoise(1.2,.15*v,position,'bandpass',520);soundTone(118,72,1,.1*v,'sine',position);break;case'quake':soundTone(76,24,.85,.45*v,'sine',position);soundNoise(.7,.3*v,position,'lowpass',360);break;case'sword':soundNoise(.2,.18*v,position,'highpass',2400);soundTone(760,240,.18,.14*v,'triangle',position);break;case'swordHit':soundTone(1250,530,.16,.2*v,'triangle',position);soundNoise(.12,.1*v,position,'highpass',4200);break;case'shieldOn':soundTone(210,840,.32,.16*v,'sine');soundTone(330,1320,.25,.08*v,'triangle',null,.04);break;case'shieldOff':soundTone(620,190,.22,.11*v,'sine');break;case'shieldHit':soundTone(980,420,.28,.18*v,'triangle');soundTone(1480,760,.2,.08*v,'sine');break;case'shieldBreak':soundNoise(.48,.3*v,null,'highpass',1900);soundTone(360,48,.65,.24*v,'sawtooth');break;case'hurt':soundTone(105,56,.24,.22*v,'sawtooth');soundNoise(.16,.12*v,null,'lowpass',480);break;case'heal':soundTone(420,790,.35,.11*v,'sine');soundTone(630,1180,.3,.07*v,'sine',null,.08);break;case'portal':soundTone(92,330,1.25,.18*v,'sine',position);soundNoise(1,.1*v,position,'bandpass',1300);break;case'teleport':soundTone(780,110,.32,.18*v,'triangle');break;case'crystal':soundTone(1650,310,.5,.2*v,'sine',position);soundNoise(.28,.12*v,position,'highpass',3800);break;case'rifle':soundNoise(.12,.34*v,position,'highpass',1800);soundTone(150,52,.18,.24*v,'square',position);break;case'step':soundNoise(.055,.045*v,null,'lowpass',260);break;case'death':soundTone(180,42,.9,.24*v,'sawtooth',position);break;case'victory':for(let i=0;i<4;i++)soundTone([262,330,392,523][i],[262,330,392,523][i],.45,.085*v,'triangle',null,i*.12);break;case'defeat':soundTone(220,55,1.2,.25*v,'sawtooth');soundTone(147,38,1.4,.16*v,'sine',null,.12);break;case'helicopter':soundTone(42,88,8.4,.2*v,'sawtooth',position);soundNoise(8.4,.12*v,position,'lowpass',240);break}}

  function choosePvpMusic(){let next=Math.floor(Math.random()*PVP_MUSIC.length);if(next===music.pvpIndex)next=(next+1)%PVP_MUSIC.length;music.pvpIndex=next;return PVP_MUSIC[next]}
  function pvpMusicVolume(time=performance.now()){if(!music.key?.startsWith('pvp'))return music.volume;const elapsed=Math.max(0,time-(music.pvpRiseStarted||time)),progress=THREE.MathUtils.clamp(elapsed/26000,0,1),rise=progress*progress*(3-2*progress);return THREE.MathUtils.lerp(.18,Math.min(1,music.volume+.1),rise)}
  function stopMusic(){if(!music.element)return;music.element.pause();music.element.removeAttribute('src');music.element.load();music.element=null}
  function playMusic(){const state=getState();if(!music.element||!music.element.paused||!music.unlocked||sound.muted||document.hidden||state.tabSuspended)return;music.element.muted=false;music.element.volume=pvpMusicVolume();music.element.play().catch(()=>{})}
  function switchMusic(key){if(music.key===key&&music.element)return;const enteringPvp=key?.startsWith('pvp')&&!music.key?.startsWith('pvp');stopMusic();music.key=key;if(enteringPvp)music.pvpRiseStarted=performance.now();const track=MUSIC_TRACKS[key];if(!track||music.failed.has(key))return;const audio=new Audio(track.url);audio.preload='metadata';audio.loop=!key.startsWith('pvp');audio.volume=pvpMusicVolume();audio.playsInline=true;audio.addEventListener('ended',()=>{if(key.startsWith('pvp')&&music.element===audio)switchMusic(choosePvpMusic())});audio.addEventListener('error',()=>{if(music.element!==audio)return;music.failed.add(key);stopMusic();if(key.startsWith('pvp')&&music.failed.size<PVP_MUSIC.length)switchMusic(choosePvpMusic())});music.element=audio;playMusic()}
  function updateMusic(){const state=getState(),wanted=getDesiredMusic();if(wanted!==music.key)switchMusic(wanted);if(document.hidden||state.tabSuspended||sound.muted){music.element?.pause();return}if(music.element){const targetVolume=pvpMusicVolume();if(Math.abs(music.element.volume-targetVolume)>.002)music.element.volume=targetVolume}playMusic()}

  return{sound,music,unlockAudio,sfx,choosePvpMusic,playMusic,updateMusic};
}
